name: profiles
version: '1.1.9'
main: org.overtime.profiles.ProfilePlugin
api-version: '1.21'

commands:
  profile:
    description: Manage player profiles
    aliases: [p]
    usage: /profile [help|add|...]
